name: CI 

on : 
  push: 
    branches : [master, dev]
  pull_request:
    branches: [master, dev]  


jobs: 
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Cloner le code 
        uses: actions/checkout@v4

      - name: Dire bonjour
        run: echo "Hello CI"      