name: CI 

on : 
  push: 
    branches : [master, dev]
  pull_request:
    branches: [master, dev]  


jobs: 
  back-end:
    runs-on: ubuntu-latest


    steps:
      - name: Cloner le code 
        uses: actions/checkout@v4

      - name: Installer PHP 8.4
        uses : shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, bcmath, gd, zip, exif, pcntl

      - name: Mettre en cache les dépendances Composer 
        uses: actions/cache@v4
        with:
          path: back-end/vendor
          key: composer-${{ hashFiles('back-end/composer.lock')}}    

      - name: Installer les dépendances Composer
        working-directory: back-end
        run: composer install --no-interaction --no-scripts --optimize-autoloader

      - name : Copier le fichier .env 
        working-directory: back-end
        run: cp .env.example .env

      - name: Générer la clé d'application
        working-directory: back-end
        run: php artisan key:generate

      - name: Lancer les test
        working-directory: back-end
        run : php artisan test

      

  front-end:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Mettre en cache les dépendances npm 
        uses: actions/cache@v4
        with:
          path: front-end/node_modules
          key: npm-${{ hashFiles('front-end/package-lock.json')}}


      - name: Installer les dépendances npm
        working-directory : front-end
        run: npm ci   

      - name: Lancer le linter
        working-directory: front-end
        run: npm run lint

      - name: Vérifier le build
        working-directory: front-end
        run: npm run build  

      
        
        
        



